spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: miro-mcp-server
        version: 1.0.0

logging:
  pattern:
    console:
  file:
    name: './miro-mcp-server.log' # лог будем писать в отдельный файл